spring:
  application:
    name: gulimall-third-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      filter:
        url-patterns: /**
    alibaba:
      oss:
        enabled: true
server:
  port: 12000

