spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.159.129
    port: 6379
server:
  port: 14000