spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      filter:
        url-patterns: /**
  thymeleaf:
    cache: false
  redis:
    host: 192.168.159.129
    port: 6379
  session:
    store-type: redis
server:
  port: 14000
  servlet:
    session:
      timeout: 30m