spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.159.129
  task:
    scheduling:
      pool:
        size: 5
server:
  port: 16000