spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      filter:
        url-patterns: /**
      enabled: true
  redis:
    host: 192.168.159.129
  task:
    scheduling:
      pool:
        size: 5
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.159.129
    port: 5672
    virtual-host: /
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://192.168.159.129:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 16000