spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      filter:
        url-patterns: /**
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.159.129
  session:
    store-type: redis
server:
  port: 13000
